server:
  port: 7061
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clip_tender?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: SaHaR@19841363
  jpa:
    hibernate.ddl-auto: validate
