server:
  port: 7061
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clip_tender?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ardehali
    password: ardehali
  jpa:
    hibernate.ddl-auto: create
